### ISSUE TITLE
hard to track character encoding issue in json file

### ISSUE THREAD

**Issue by KGBicheno** [KGBicheno/KGB_EDITS#3]
In the function style_guide(), the NCA_style_guide.json file throws a character encoding exception that I can't track down manually or through parsing it through validators.

Here's a link to the Json file: [NCA Style Guide ](https://github.com/KGBicheno/KGB_EDITS/blob/cogs-1/NCA_style_guide.json) 

```python
    @commands.command()
    async def style_guide(self, ctx, search_term):
        with open('NCA_style_guide.json', 'r') as reference:
            guide = json.load(reference)
        pprint(guide)
        for entry, answer in guide:
            if search_term == entry:
                result = ("> Entry: " + entry +
                          "> Usage: " + answer)
                await ctx.send(result)
```

```bash
Traceback (most recent call last):
  File "E:\Users\websi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "E:\KGB PROJECTS\KGB_Golem\Brook\code\cogs\news.py", line 208, in style_guide
    guide = json.load(reference)
  File "E:\Users\websi\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "E:\Users\websi\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2507: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Users\websi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "E:\Users\websi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "E:\Users\websi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2507: character maps to <undefined>
``

**Comment by KGBicheno** [comment]
Added encoding argument to file handler, worked like a charm.
